
#include QMK_KEYBOARD_H
#include "quantum.h"
#include "artsey.h"
#include "keymap_combo.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_ARTSEY_BASE] = LAYOUT_ortho_3x10(
A_S,A_T,A_R,A_A,KC_NO,KC_NO,A_A,A_R,A_T,A_S,
A_O,A_I,A_Y,A_E,KC_NO,KC_NO,A_E,A_Y,A_I,A_O,
KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO,KC_NO

  ),

  [_ARTSEY_NUM] = LAYOUT_ortho_3x10(
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,A_1, A_2, A_3, KC_NO,
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,A_4, A_5, A_6, KC_NO,
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS

  ),


  [_ARTSEY_SYM] = LAYOUT_ortho_3x10(
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_NO,KC_BSLS,KC_SCOLON,KC_GRAVE,
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_NO,KC_MINUS,KC_EQUAL,KC_NO,
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS

  ),


  [_ARTSEY_BRAC] = LAYOUT_ortho_3x10(
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_NO, KC_LPRN,KC_RPRN,KC_LCBR,
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_NO, KC_LBRACKET,KC_RBRACKET,KC_RCBR,
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS

  ),

  [_ARTSEY_NAV] = LAYOUT_ortho_3x10(
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_HOME, KC_UP, KC_END,KC_NO,
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_LEFT, KC_DOWN, KC_RIGHT,KC_NO,
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS

  ),

  [_ARTSEY_MOU] = LAYOUT_ortho_3x10(
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_MS_BTN1,KC_MS_UP,KC_MS_BTN2,KC_PGUP,
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_MS_LEFT,KC_MS_DOWN,KC_MS_RIGHT,KC_PGDN,
KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS

  ),




};
